### ISSUE TITLE
While trying to test the discord owner ingame name.

### ISSUE THREAD

**Issue by TobiasEscalante** [davedehaan/GoodBot#14]
Unable to set your name: Missing Permissions

**Comment by rch317** [comment]
I'm getting this too,  is there a fix for this?  Bot has admin rights.

**Comment by davedehaan** [comment]
Hey guys --
This happens when the bot's highest role is lower than the highest role of the person's permission it's trying to adjust.

![image](https://user-images.githubusercontent.com/3186052/89923711-fea20b80-dbce-11ea-9339-88574f8a67f3.png)

Under Roles, a bot can only adjust the permissions of users it it higher than in the hierarchy.  Also, it can never adjust the name of the administrator within the discord.

**Comment by davedehaan** [comment]
I added a further error message in c535677ad4e7157c493f88ac54cf15add565eca6 -- this should hopefully make the situation more clear to people running into this error.

**Comment by rch317** [comment]
Ohhh, so even though it has admin... it still has to sit above other roles in the listing?  I'll try that out, thanks.
